# make it explicit that we favor the new container-based travis workers
sudo: false

language: python

matrix:
    include:
        - python: 3.5
          env: TOXENV=py35
        - python: 3.6
          env: TOXENV=py36
        - python: 3.6
          env: TOXENV=docs
        - python: 3.6
          env: TOXENV=flake8

script: tox

before_install:
  - pip install codecov tox

after_success:
  - tox -e coverage-report
  - codecov


notifications:
  email: true

{% if cookiecutter.use_pypi_deployment_with_travis == 'y' -%}
# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: {{ cookiecutter.pypi_username }}
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: {{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}
    condition: $TOXENV == py27
{%- endif %}
